VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes

QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

RGBLIGHT_ENABLE = yes
MAGIC_ENABLE = yes
MIDI_ENABLE = no
BLUETOOTH_ENABLE = no
BACKLIGHT_ENABLE = no
OLED_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = yes

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

VIAL_ENCODERS_ENABLE = yes

CONVERT_TO = kb2040
